"""Differential directed tests: one minimal program per instruction in an
extension's table (``specs/<ext>/instructions.json``, generated by
``vext.gen_isa_table`` from riscv-opcodes). Each program executes the
instruction once and exits; Spike is the oracle via cospike, so no expected
output is encoded. Coverage is 100% by construction — the table IS the
extension's closed instruction set, so the emitted set covers every instruction.
"""
import json
import os
import random

_SPECS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "specs")

N_EXEC = 40   # random executions per instruction (Spike judges each commit)

# A `main()` that runs the instruction N_EXEC times on random operands, then
# returns 0. The RiscvBuildNode harness links htif_nano.specs, which supplies
# _start/tohost and calls main (so we must NOT define those). The cospike
# comparison happens per committed instruction, so the test needs no self-check
# — it only has to execute the instruction. Build with lang="asm" + -march=...
_HARNESS = """\
.text
.globl main
main:
  {body}
  li a0, 0
  ret
"""


def _emit(mnem: str, args: list[str], n: int = N_EXEC) -> str:
    # Deterministic per instruction (str seed uses a stable hash) so the same
    # tests regenerate every run — reproducible, but n distinct random inputs.
    rng = random.Random(mnem)
    body: list[str] = []
    for _ in range(n):
        loads, ops = [], []
        for a in args:
            if a == "rd":
                ops.append("a0")
            elif a == "rs1":
                loads.append(f"li a1, 0x{rng.getrandbits(64):016x}"); ops.append("a1")
            elif a == "rs2":
                loads.append(f"li a2, 0x{rng.getrandbits(64):016x}"); ops.append("a2")
            elif a == "rnum":                       # AES round constant 0..10
                ops.append(str(rng.randint(0, 10)))
            elif a.startswith("shamt"):             # shamtw 0..31 / shamtd 0..63
                ops.append(str(rng.randint(0, 31 if a.endswith("w") else 63)))
            else:
                ops.append("0")
        body += loads
        body.append(f"{mnem} {', '.join(ops)}")
    return _HARNESS.format(body="\n  ".join(body))


def instr_table(ext: str) -> dict[str, list[str]]:
    with open(os.path.join(_SPECS, ext, "instructions.json")) as f:
        return json.load(f)


def emit_tests(ext: str) -> dict[str, str]:
    """{f'{ext}-{mnemonic}': asm_text} — one differential test per instruction."""
    return {f"{ext}-{m}": _emit(m, args) for m, args in instr_table(ext).items()}
