// Scalar-crypto instruction enum, `included into riscv_instr_name_t. ZK_-prefixed
// to avoid clashing with riscv-dv's existing bitmanip enum members (andn, ror,
// rev8, pack, clmul, ...); get_instr_name() strips the prefix.
ZK_AES64DS,
ZK_AES64DSM,
ZK_AES64ES,
ZK_AES64ESM,
ZK_AES64IM,
ZK_AES64KS1I,
ZK_AES64KS2,
ZK_ANDN,
ZK_BREV8,
ZK_CLMUL,
ZK_CLMULH,
ZK_ORN,
ZK_PACK,
ZK_PACKH,
ZK_PACKW,
ZK_REV8,
ZK_ROL,
ZK_ROLW,
ZK_ROR,
ZK_RORI,
ZK_RORIW,
ZK_RORW,
ZK_SHA256SIG0,
ZK_SHA256SIG1,
ZK_SHA256SUM0,
ZK_SHA256SUM1,
ZK_SHA512SIG0,
ZK_SHA512SIG1,
ZK_SHA512SUM0,
ZK_SHA512SUM1,
ZK_XNOR,
ZK_XPERM4,
ZK_XPERM8,
